# Generated by Django 3.2 on 2023-01-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('c_value', models.CharField(choices=[('AG', 'Agency'), ('MT', 'Material')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
