# Generated by Django 3.2 on 2023-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='c_value',
            field=models.CharField(choices=[('AG', 'Agency'), ('MT', 'Material')], default='AG', max_length=100),
        ),
    ]
